### ISSUE TITLE
Not working without USB Keyboard

### ISSUE THREAD

**Issue by dmelladom** [apparentVJ/ofxRPiTouch#1]
Hi!
I am having troubles with the add on. It works perfectly great when I have a USB keyboard attached to the board, but it doesn't if booted without it.
Any idea why that can be happening and how can it be solved?
Thanks in advance!
D!

**Comment by steeley** [comment]
The device ID changes depending on what USB is plugged. Thats why the line in setup says:
touch.init("/dev/input/event1");	// change according to your setup (evade)

Use the command line tool evtest to see you peripherals.

I don't think you can dynamically change this, or scan for the touchscreen with this addon.
